src/Entity/AbstractEntity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\MappedSuperclass
 * @ORM\HasLifecycleCallbacks
 */
abstract class AbstractEntity
{

    const ENTITY_ID = 'id';
    const ENTITY_CREATE = 'entity_create';
    const ENTITY_UPDATE = 'entity_update';
    const ENTITY_REMOVE = 'entity_remove';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="bigint")
     */
    protected $id;
    /**
     * @ORM\Column(type="datetime",nullable=false)
     */
    protected $entity_create;
    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    protected $entity_update;
    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    protected $entity_remove;

    /**
     * @ORM\PrePersist
     * @throws \Exception
     */
    final public function lifecycleCreate()
    {

        if (empty($this->EntityCreate)) {
            $this->entity_create = new \DateTime("now");
        }
    }

    /**
     * @ORM\PreUpdate
     * @throws \Exception
     */
    final public function lifecycleUpdate()
    {

        $this->entity_update = new \DateTime("now");
    }

    /**
     * @throws \Exception
     */
    final public function __toArray()
    {

        $array = get_object_vars($this);
        foreach ($array as $key => $value) {
            if ($value instanceof \DateTime) {
                $array[$key] = $value->format('d.m.Y H:i:s');
            }
        }

        return $array;
    }

    /**
     * @return \DateTime
     */
    public function getEntityCreate()
    {

        if (is_object($this->entity_create)) {
            return clone $this->entity_create;
        }
        return $this->entity_create;
    }

    /**
     * @return null|\DateTime
     */
    public function getEntityUpdate()
    {

        if (is_object($this->entity_update)) {
            return clone $this->entity_update;
        }
        return $this->entity_update;
    }

    /**
     * @param AbstractEntity $requiredEntity
     *
     * @return \DateTime|null
     * @throws \ReflectionException
     * @throws \Exception
     */
    public function getEntityRemove(AbstractEntity $requiredEntity = null)
    {

        // Default
        if ($this->entity_remove) {
            return $this->entity_remove;
        }

        // Joined Element Overload
        if (null === $requiredEntity) {
            // No Overload
            return $this->entity_remove;
        } else {
            $method = 'getService' . (new \ReflectionClass($requiredEntity))->getShortName();
            if (method_exists($this, $method)) {
                /** @var bool|AbstractEntity $table_join */
                $table_join = $this->$method();
                if ($table_join) {
                    // Exists
                    if ($table_join->getEntityRemove()) {
                        return $table_join->getEntityRemove();
                    } else {
                        return $this->entity_remove;
                    }
                } else {
                    // Missing Element
                    return new \DateTime();
                }
            } else {
                // Missing Method
                return $this->entity_remove;
            }
        }
    }

    /**
     * @param bool $Toggle
     *
     * @return AbstractEntity
     * @throws \Exception
     */
    public function setEntityRemove($Toggle = true)
    {

        if ($Toggle) {
            $this->entity_remove = new \DateTime("now");
        } else {
            $this->entity_remove = null;
        }
        return $this;
    }

    /**
     * Return Object-Id
     * Fix: Doctrine - Entity can't be converted to 'string' while getting Entity-Id
     *
     * @return string
     */
    final public function __toString()
    {

        return strval($this->getId());
    }

    /**
     * @return integer
     */
    final public function getId()
    {

        return $this->id;
    }

    /**
     * @param integer $Id
     */
    final public function setId($Id)
    {

        $this->id = $Id;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    final public function getEntityShortName()
    {

        return (new \ReflectionClass($this))->getShortName();
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    final public function getEntityFullName()
    {

        return (new \ReflectionClass($this))->getName();
    }

    /**
     * @param mixed $value
     * @return float
     */
    protected function sanitizeNumber($value)
    {

        if (is_numeric($value)) {
            // Default
            return (float)$value;
        } else {
            // Locale
            if (class_exists('Locale') && class_exists('NumberFormatter')) {
                $locale = \Locale::acceptFromHttp($_SERVER['HTTP_ACCEPT_LANGUAGE']);
                $convert = (new \NumberFormatter($locale, \NumberFormatter::TYPE_DOUBLE));
                if (false !== $convert->parse($value)) {
                    return (float)$convert->parse($value);
                }
            }
            // Fallback
            return (float)str_replace(',', '.', str_replace('.', '', $value));
        }
    }
}

src/Controller/GraphController.php
<?php

namespace App\Controller;

use App\Entity\Process;
use App\Helper\GraphHelper;
use App\Repository\ArticleRepository;
use App\Repository\ProcessRepository;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class GraphController
 * @package App\Controller
 *
 * @Route("/graph")
 */
class GraphController extends AbstractController
{

    /**
     * @var ArticleRepository $articleRepository
     */
    private $articleRepository;
    /**
     * @var ProcessRepository $processRepository
     */
    private $processRepository;

    /**
     * GraphController constructor.
     * @param ArticleRepository $articleRepository
     * @param ProcessRepository $processRepository
     */
    public function __construct(ArticleRepository $articleRepository, ProcessRepository $processRepository)
    {
        $this->articleRepository = $articleRepository;
        $this->processRepository = $processRepository;
    }


    /**
     * @Route("/", name="graph.index", methods="GET")
     * @return Response
     * @throws NonUniqueResultException
     */
    public function index()
    {
        return $this->render('graph/index.html.twig', [
            'articles' => $this->articleRepository->findAll(),
            'processes' => $this->processRepository->getProgressList()
        ]);
    }

    /**
     * @Route("/{id}/delete", name="graph.delete")
     *
     * @param Request $request
     * @param string $id
     *
     * @return Response
     */
    public function delete(Request $request, string $id = ''): Response
    {
        $process = $this->processRepository->findOneBy([Process::PROPERTY_PROCESS => $id]);

        if ($process && $this->isCsrfTokenValid('delete' . $process->getProcess(), $request->get('_token'))) {

            $processes = $this->processRepository->findBy([Process::PROPERTY_PROCESS => $process->getProcess()]);
            $em = $this->getDoctrine()->getManager();
            foreach( $processes as $process ) {
                $em->remove($process);
            }
            $em->flush();
            $this->addFlash('success', 'Daten wurden gelöscht');
            return $this->redirectToRoute('graph.index');
        }
        $this->addFlash('warning', 'Daten konnten nicht gelöscht werden');

        return $this->redirectToRoute('graph.index');
    }

    /**
     * @Route("/{id}", name="graph.chart", methods="GET")
     * @param string $id
     * @return Response
     * @throws NonUniqueResultException
     */
    public function chart(string $id = '')
    {

        $processList = $this->processRepository->findBy( [Process::PROPERTY_PROCESS => $id] );

//        $article = $this->articleRepository->find($id);

//        $processList = $article->getProcessList();

        $current = false;
        if (!empty($processList)) {

            /** @var Process[] $data */
            $data = $processList;

            $article = current($data)->getArticle();

            $current = $article->getName().' - '.date('d.m.Y H:i:s',strtotime($this->processRepository->getImportTimestamp($data[0]->getProcess())));

            $scf = array_map(function (Process $p) {
                return $p->getCounterFrame();
            }, $data);
            $stp = array_map(function (Process $p) {
                return $p->getThresholdPixel();
            }, $data);
            $scv = array_map(function (Process $p) {
                return $p->getCurrentValue();
            }, $data);
            $svv = array_map(function (Process $p) {
                return $p->getVoltageValue();
            }, $data);
            $stv = array_map(function (Process $p) {
                return $p->getTemperatureValue();
            }, $data);
            $srv = array_map(function (Process $p) {
                return '# '.(string)$p->getRemarkValue();
            }, $data);


            $minValue = $data[0]->getTimestamp()->getTimestamp();

            $zc = new GraphHelper(
                $article->getName(),
                'myChart',
                $minValue . '000'
            );

            $zc->setSeries('Spannung', $svv);
            $zc->setSeries('Stromstärke', $scv);
            $zc->setSeries('Funkenintensität', $stp);
            $zc->setSeries('Temperatur', $stv);
//            $zc->setSeries('Frame', $scf);
//            $zc->setSeries('Status', $srv);
        } else {
            $zc = new GraphHelper('Not found');
        }

        return $this->render('graph/index.html.twig', [
            'chart' => $zc->getChart(),
            'articles' => $this->articleRepository->findAll(),
            'processes' => $this->processRepository->getProgressList(),
            'current' =>  $current
        ]);
    }
}

templates/graph/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }}
{% endblock %}

{% block form %}
    <span class="lead">Visualisierung</span>
    {% if chart is defined %}
        <div>{{ current }}</div>
        <a name="graph"></a>
        <div id="myChart" style="border: 1px solid lightgray;"></div>
    {% else %}
        <div>Bitte einen Import zur Visualisierung wählen</div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if chart is defined %}
        {{ chart|raw }}
    {% endif %}
{% endblock %}

{% block body %}

    <span class="lead">Daten</span>
    <hr class="mt-1"/>
    <div class="p-2 bg-light">
        <table class="table table-striped table-bordered make-dt">
            <thead>

            <tr>
                <th rowspan="2">Produkt</th>
                <th rowspan="2">Konfiguration</th>

                <th colspan="4">Spannung</th>
                <th colspan="3">Funkenintensität</th>

                <th>Stromstärke</th>
                <th>Temperatur</th>

                <th rowspan="2" style="width: 1%;">Angelegt</th>
                <th rowspan="2" style="width: 1%;">Datensätze</th>
            </tr>
            <tr>
                <th class="small">Obere Grenze</th>
                <th class="small">Hysterese</th>
                <th class="small">Startwert</th>
                <th class="small">Schrittweite Änderung</th>

                <th class="small">Grenze</th>
                <th class="small">Hysterese</th>
                <th class="small">Schwellwert</th>

                <th class="small">Untere Grenze</th>

                <th class="small">Maximum</th>
            </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                {% for config in article.configList %}
                    <tr>
                        <td>{% if( article is not empty ) %}{{ article.name }}{% else %}<span
                                    class="alert alert-danger">Kein Produkt zugeordnet</span>{% endif %}</td>
                        <td>{{ config.overlayText }}</td>

                        <td>{{ config.voltageLimit }}</td>
                        <td>{{ config.voltageHysteresis }}</td>
                        <td>{{ config.voltageStart }}</td>
                        <td>{{ config.voltageStep }}</td>

                        <td>{{ config.intensityLimit }}</td>
                        <td>{{ config.intensityHysteresis }}</td>
                        <td>{{ config.intensityThreshold }}</td>

                        <td>{{ config.currentLimit }}</td>

                        <td>{{ config.temperatureMaximum }}</td>
                        <td>{{ config.entityCreate|date('d.m.Y H:i:s') }}</td>

                        <td class="text-center">
                            {% if(processes is empty) %}
                                Keine Daten vorhanden<br/>
                                {% if( config.article is not empty ) %}
                                    <div class="btn-group">
                                        <a href="{{ path('data.select', {'id': config.id}) }}" class="btn btn-sm btn-success"><span class="fa fa-download"></span> Datei importieren</a>
                                    </div>
                                {% endif %}
                            {% else %}
                                <table class="table table-sm">
                                    <thead>
                                    <tr>
                                        <th>Importiert</th>
                                        <th>Daten&nbsp;Von</th>
                                        <th>Daten&nbsp;Bis</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for process in processes %}
                                        {% if( process.article == article.id and process.config == config.id ) %}
                                            <tr>
                                                <td>
                                                    {{ process.import|date('d.m.Y') }}
                                                    <br/>{{ process.import|date('H:i:s') }}
                                                    {#                                            <div class="small text-muted">ID: {{ process.process }}</div>#}
                                                </td>
                                                <td>
                                                    {{ process.min|date('d.m.Y') }}<br/>{{ process.min|date('H:i:s') }}
                                                </td>
                                                <td>
                                                    {{ process.max|date('d.m.Y') }}<br/>{{ process.max|date('H:i:s') }}
                                                </td>
                                                <td>
                                                    <div class="btn-group">
                                                        <a href="{{ path('graph.chart', {'id': process.process}) }}#graph"
                                                           class="btn btn-sm btn-success">Visualisieren</a>
                                                        <a href="{{ path('graph.delete', {'id': process.process, '_token': csrf_token('delete'~process.process) } ) }}"
                                                           class="btn btn-sm btn-danger"
                                                           onclick="return confirm('Wirklich löschen?')"
                                                        >
                                                            <span class="fa fa-trash-alt"></span>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}